<?php

namespace Diolan12;

/**
 * A class that represents a network of cable routes.
 * Generated by OpenAI ChatGPT [Mar 14 Version](https://help.openai.com/en/articles/6825453-chatgpt-release-notes)
 */
class Dijkstra
{
    private $prefix = '#';
    private $vertices = [];
    private $edges = [];

    public function __construct($graph = [])
    {
        $prefixedVertices = [];
        foreach ($graph as $k => $edges) {
            $prefixedName = $this->setPrefix($k);
            $prefixedVertices[$prefixedName] = [];
            foreach ($edges as $edgeKey => $edgeValue) {
                $prefixedVertices[$prefixedName][$this->setPrefix($edgeKey)] = $edgeValue;
            }
        }
        $this->vertices = $prefixedVertices;
    }

    private function setPrefix(string $value)
    {
        return $this->prefix . $value;
    }
    private function unPrefix(string $value)
    {
        return substr($value, 1);
    }

    /**
     * Return Dijkstra's instance
     * @return \Diolan12\Dijkstra
     */
    public static function instance($graph = [])
    {
        return new self($graph);
    }

    /**
     * Add a vertex to the graph with its neighboring edges.
     *
     * @param string $name The name of the vertex.
     * @param array $edges An associative array representing the neighboring vertices and their edge weights.
     * @return \Diolan12\Dijkstra
     */
    public function addVertex($name, $edges)
    {
        // ensure vertices and edges exist
        $this->vertices[$this->setPrefix($name)] ??= [];
        $this->edges[$this->setPrefix($name)] ??= [];

        $prefixedName = [];
        $return = $this;

        foreach ($edges as $key => $value) {
            if (gettype($value) == 'array' && isset($value['weight'])) $return = $return->addEdge(src: $name, dest: $key, weight: $value['weight'], data: $value);

            elseif (gettype($value) == 'array' && gettype(array_values($value)[0]) == 'array') {
                foreach ($value as $edge) {
                    $return = $return->addEdge(src: $name, dest: $key, weight: $edge['weight'], data: $edge);
                }
            }

            else $return = $return->addEdge(src: $name, dest: $key, weight: $value);
        }

        return $return;
    }

    /**
     * Add an edge between two vertices with a given weight.
     *
     * @param string $src The source vertex.
     * @param string $dest The destination vertex.
     * @param int $weight The weight or cost of the edge.
     * @return \Diolan12\Dijkstra
     */
    public function addEdge($src, $dest, $weight, ?string $tag = null, array $data = [], $reversible = false)
    {
        if (!isset($this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)])) {
            $this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)] = $weight;
        }

        else {
            $this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)] = ($this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)] > $weight) ? $weight : $this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)];
        }

        if (!isset($this->edges[$this->setPrefix($src)][$this->setPrefix($dest)])) {
            $this->edges[$this->setPrefix($src)][$this->setPrefix($dest)] = [];
        }

        $this->edges[$this->setPrefix($src)][$this->setPrefix($dest)][] = [
            'tag' => $tag ?? ($src . ' to ' . $dest),
            'data' => $data,
            'weight' => $weight,
            'src' => $src,
            'dest' => $dest
        ];

        if ($reversible) return $this->addEdge(src: $dest, dest: $src, weight: $weight, tag: $tag, data: $data);
        else return $this;
    }

    /**
     * Dijkstra's shortest path algorithm
     * [Wikipedia](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)
     * @see https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm
     * @throws \Diolan12\NoPathException
     * @return array
     */
    public function findShortestPath($start, $end, $verbose = false)
    {
        // sort the edges if verbose is required
        if ($verbose) {
            foreach ($this->edges as $origin) {
                foreach ($origin as &$destination) {
                    array_multisort(array_column($destination, 'weight'), SORT_ASC, $destination);
                }
            }
        }

        $start = $this->setPrefix($start);
        $end = $this->setPrefix($end);
        $distances = [];
        $visited = [];
        $previous = [];

        foreach ($this->vertices as $vertex => $edges) {
            $distances[$vertex] = INF;
            $visited[$vertex] = false;
            $previous[$vertex] = null;
        }

        $distances[$start] = 0;

        if (!isset($visited[$end])) {
            throw new NoPathException('Route not found "' . $this->unPrefix($end) . '"');
        }
        while ($visited[$end] === false) {
            $current = null;
            $minDist = INF;

            foreach ($distances as $vertex => $dist) {
                if (array_key_exists($vertex, $visited)){
                    if ($visited[$vertex] === false && $dist <= $minDist) {
                        $minDist = $dist;
                        $current = $vertex;
                    }
                } else throw new NoPathException('Edge "' . $this->unPrefix($vertex) . '" not found');
            }

            foreach ($this->vertices[$current] as $neighbor => $cost) {
                $alt = $distances[$current] + $cost;

                if ($alt < $distances[$neighbor]) {
                    $distances[$neighbor] = $alt;
                    $previous[$neighbor] = $current;
                }
            }

            $visited[$current] = true;
        }

        $path = [];
        $current = $end;

        while ($current !== $start) {
            if ($current == null) {
                throw new NoPathException('Route not found "' . $this->unPrefix($end) . '"');
            }
            array_unshift($path, $current);
            $current = $previous[$current];
        }

        array_unshift($path, $start);

        foreach ($path as $k => $p) {
            $path[$k] = $this->unPrefix($p);
        }

        if (!$verbose) return $path;
        else {
            // cost and steps setup
            $cost = 0;
            $edges = [];
            $merged = [];

            // figure out all the routings - use minimum weight edge for each segment
            foreach (range(0, sizeof($path)-2) as $i) {
                $src = $this->setPrefix($path[$i]);
                $dest = $this->setPrefix($path[$i+1]);

                // Find the edge with minimum weight for this segment
                $minEdge = $this->edges[$src][$dest][0];
                $minWeight = $minEdge['weight'];

                foreach ($this->edges[$src][$dest] as $edge) {
                    if ($edge['weight'] < $minWeight) {
                        $minWeight = $edge['weight'];
                        $minEdge = $edge;
                    }
                }

                $edges[] = $minEdge;
                $cost += $minEdge['weight'];

                if ($i == 0) $merged[] = $path[$i];
                $merged[] = $minEdge;
                if ($i != sizeof($path)-2) $merged[] = $path[$i+1];
                if ($i == sizeof($path)-2) $merged[] = $path[$i+1];
            }

            return [
                'cost' => $cost,
                'edges' => $edges,
                'path' => $path,
                'merged' => $merged
            ];
        }
    }

    /**
     * Yen's Algorithm
     * [Wikipedia](https://en.wikipedia.org/wiki/Yen%27s_algorithm)
     * @see https://en.wikipedia.org/wiki/Yen%27s_algorithm
     * @throws \Diolan12\NoPathException
     * @return array
     */
    public function findNShortestPaths($start, $end, $n = 2, $verbose = false)
    {
        if ($n == 0) $n = PHP_INT_MAX;

        $originalEdges = json_decode(json_encode($this->edges), true);
        $originalVertices = json_decode(json_encode($this->vertices), true);

        $paths = [];
        $seenPathSignatures = [];

        // Try all possible first edges from the start node
        $startPrefix = $this->setPrefix($start);
        if (!isset($originalEdges[$startPrefix])) {
            return [];
        }

        // Enumerate all edge options from first hop
        foreach ($originalEdges[$startPrefix] as $firstDest => $edgeOptions) {
            foreach ($edgeOptions as $firstEdge) {
                $firstNode = $this->unPrefix($firstDest);

                // Skip if it creates a cycle (revisiting start node)
                if ($firstNode === $start) {
                    continue;
                }

                // If first node IS the destination, create a single-hop path
                if ($firstNode === $end) {
                    $restPath = [
                        'cost' => 0,
                        'path' => [$end],
                        'edges' => [],
                        'merged' => [$end]
                    ];
                } else {
                    // Try finding paths from this first node to destination
                    // Remove the start node from graph to prevent cycles
                    try {
                        $this->edges = json_decode(json_encode($originalEdges), true);
                        $this->vertices = json_decode(json_encode($originalVertices), true);

                        // Remove start node to prevent returning to it
                        $startPrefix = $this->setPrefix($start);
                        unset($this->vertices[$startPrefix]);
                        foreach ($this->vertices as &$neighbors) {
                            unset($neighbors[$startPrefix]);
                        }

                        $restPath = $this->findShortestPath(start: $firstNode, end: $end, verbose: true);
                    } catch (NoPathException $e) {
                        // This path doesn't lead to destination
                        continue;
                    }
                }

                try {
                    $fullPath = array_merge([$start], $restPath['path']);

                    // Check for cycles in the full path
                    if (count($fullPath) !== count(array_unique($fullPath))) {
                        continue; // Skip paths with cycles
                    }

                    // Calculate total cost
                    $totalCost = $firstEdge['weight'] + $restPath['cost'];
                    $allEdges = array_merge([$firstEdge], $restPath['edges']);

                    // Build merged array (node, edge, node, edge, ..., node)
                    $merged = [$start, $firstEdge];
                    foreach ($restPath['merged'] as $item) {
                        if (!in_array($item, $merged)) {
                            $merged[] = $item;
                        }
                    }

                    $pathSig = implode('->', $fullPath) . '|' . implode(',', array_map(fn($e) => $e['weight'], $allEdges));
                    if (!isset($seenPathSignatures[$pathSig])) {
                        $paths[] = [
                            'cost' => $totalCost,
                            'path' => $fullPath,
                            'edges' => $allEdges,
                            'merged' => $merged
                        ];
                        $seenPathSignatures[$pathSig] = true;
                    }
                } catch (NoPathException $e) {
                    // This path doesn't lead to destination
                }
            }
        }

        // Sort by cost
        array_multisort(array_column($paths, 'cost'), SORT_ASC, $paths);

        // Restore original graph
        $this->edges = $originalEdges;
        $this->vertices = $originalVertices;

        return array_slice($paths, 0, $n);
    }
}